import type {
  PresentationAsset,
  PresentationAssetId,
} from "@/lib/presentation/presentation-types";

export const presentationAssetRegistry: Readonly<
  Record<PresentationAssetId, PresentationAsset>
> = {
  "go-bottle": {
    id: "go-bottle",
    title: "Everyday Bottle",
    category: "product",
    layout: "product-portrait",
    tags: ["go", "everyday", "bottle", "portable"],
    alt: "The compact Everyday Bottle",
    media: { kind: "image", src: "/presenter/everyday-bottle.png" },
    fit: "contain",
  },
  "pro-bottle": {
    id: "pro-bottle",
    title: "Advanced Bottle",
    category: "product",
    layout: "product-portrait",
    tags: ["pro", "advanced", "bottle"],
    alt: "The Advanced Bottle",
    media: { kind: "image", src: "/presenter/advanced-bottle.png" },
    fit: "contain",
  },
  "go-vs-pro": {
    id: "go-vs-pro",
    title: "Product comparison",
    category: "comparison",
    layout: "wide-comparison",
    tags: ["go", "pro", "comparison", "products"],
    alt: "The Everyday Bottle and Advanced Bottle shown together",
    media: { kind: "image", src: "/presenter/bottles-comparison.png" },
    fit: "contain",
  },
  "hydrogen-water": {
    id: "hydrogen-water",
    title: "Hydrogen water",
    category: "infographic",
    layout: "diagram",
    tags: ["hydrogen", "water", "molecular", "infographic"],
    alt: "Diagram explaining molecular hydrogen in water",
    media: { kind: "image", src: "/presenter/hydrogen-infographic.svg" },
    fit: "contain",
  },
  "oxidative-stress": {
    id: "oxidative-stress",
    title: "Oxidative stress",
    category: "infographic",
    layout: "diagram",
    tags: ["oxidative stress", "infographic"],
    alt: "Diagram explaining oxidative stress",
    media: {
      kind: "image",
      src: "/presenter/oxidative-stress-infographic.svg",
    },
    fit: "contain",
  },
  "hydrogen-process": {
    id: "hydrogen-process",
    title: "Hydrogen process",
    category: "infographic",
    layout: "diagram",
    tags: ["hydrogen", "production", "electrolysis", "membrane"],
    alt: "Exploded view of the membrane and electrode module",
    media: { kind: "image", src: "/presenter/electrolysis-membrane.png" },
    fit: "contain",
  },
  "hydrogen-inhalation": {
    id: "hydrogen-inhalation",
    title: "Hydrogen inhalation",
    category: "feature",
    layout: "feature-detail",
    tags: ["hydrogen", "inhalation", "cannula"],
    alt: "The inhalation tube and nasal cannula accessory",
    media: { kind: "image", src: "/presenter/inhalation.png" },
    fit: "contain",
  },
  "premium-materials": {
    id: "premium-materials",
    title: "Premium materials",
    category: "feature",
    layout: "feature-detail",
    tags: ["materials", "glass", "titanium", "components"],
    alt: "Detail of the bottle's clear premium vessel",
    media: { kind: "image", src: "/presenter/premium-materials.png" },
    fit: "contain",
  },
  mineralisation: {
    id: "mineralisation",
    title: "Mineralisation",
    category: "feature",
    layout: "feature-detail",
    tags: ["mineralisation", "mineralization", "cartridge"],
    alt: "Mineralisation media used with the Advanced Bottle",
    media: { kind: "image", src: "/presenter/mineralisation.jpg" },
    fit: "cover",
  },
  charging: {
    id: "charging",
    title: "Charging",
    category: "feature",
    layout: "feature-detail",
    tags: ["charging", "battery", "usb-c", "power"],
    alt: "The Advanced Bottle active with its illuminated base",
    media: { kind: "image", src: "/presenter/charging.png" },
    fit: "contain",
  },
  maintenance: {
    id: "maintenance",
    title: "Care and maintenance",
    category: "feature",
    layout: "feature-detail",
    tags: ["maintenance", "cleaning", "care", "storage"],
    alt: "The bottle and its precision internal components",
    media: { kind: "image", src: "/presenter/maintenance.png" },
    fit: "contain",
  },
};

export function getPresentationAsset(assetId: PresentationAssetId) {
  return presentationAssetRegistry[assetId];
}
